### ISSUE TITLE
missing library?

### ISSUE THREAD

**Issue by dackdel** [internetfriendsforever/permutable#28]
cannot find 'dist/esm.js' or am i missing something :P 
![Screenshot-20201025035334-448x151](https://user-images.githubusercontent.com/380951/97094864-b2675300-1676-11eb-8e82-93d28228bcde.png)

**Comment by dackdel** [comment]
also link to the unpkg.com file in demo example works when i paste it in the browser but not when i try to run locally. had to copy paste replace https://unpkg.com/permutable@0.2.19/dist/esm.js?module with this destination link?

**Comment by danielmahal** [comment]
Yes, you are right, this is poorly documented.

So, JavaScript has many different ways of defining modules.

Permutable is compiled in three different ways:
- [esm](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) (modern way)
- [iife](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) (old-school way)
- [commonjs](https://en.wikipedia.org/wiki/CommonJS) (node.js/webpack/browserify etc.)

This let's you use Permutable in different development environments.

The recommended way of using Permutable is with _esm_. Sadly, [it does not work](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Other_differences_between_modules_and_standard_scripts) with the `file://` protocol, so you have to do your local development through a development server so it's loaded through `http://`. Any server which serves the files statically should work here.

If you don't want to use a development server, you could use the old-school _iife_ version. It works with the `file://` protocol. It would go something like this:

```html
<script src="https://unpkg.com/permutable@0.2.21/dist/iife.js"></script>
<script type="module">
  permutable.run({
    // ...
  })
</script>
```
